### ISSUE TITLE
Expect to support Linux/Arm64 container architecture

### ISSUE THREAD

**Issue by fejich** [williamjacksn/docker-caddy-lego#51]
Expect to run on machines with ARM processors

**Comment by williamjacksn** [comment]
@fejich Please pull and test the `latest` tag for this image on linux/arm64 and let me know if it is working.

**Comment by fejich** [comment]
Thanks, it works fine

```
# docker exec caddy-lego caddy version
v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=
```
